### ISSUE TITLE
Improve Explicit Constructors

### ISSUE THREAD

**Issue by CursedRock17** [ros2/message_filters#128]
As part of pull request #125, `cpplint` suggests we mark all single param constructors as `explicit` as it is a good practice for writing c++ code. Technically marking constructors as `explicit` constitutes an API break, so to prevent `cpplint` from going off they're marked as `NOLINT`. An example of an API break from these constructors is with [`Synchronizer`](https://github.com/ros2/message_filters/blob/rolling/include/message_filters/synchronizer.h#L207), in which the `Policy` must be created and initialized [first](https://github.com/ros2/message_filters/blob/b8dbbf865506632139c9ea7202ea5a95e5cdaee2/test/test_exact_time_policy.cpp#L121-L122), while much of the community just passes `queue_size` straight to their constructor. We should find a way to make these constructors explicit, while preventing API breaks

**Comment by clalancette** [comment]
> I believe it would be fine to go ahead and break API on rolling, we just need to account for it in the next release version increment.

I don't generally disagree, though I do think we should do a quick check of downstream packages to see what the extent of the breakage is going to be.
