### ISSUE TITLE
perception_pcl update causes compiler error for Ros2 humble

### ISSUE THREAD

**Issue by AlexandruSopt** [ros2/message_filters#161]
The update from perception_pcl : 
https://github.com/ros-perception/perception_pcl/pull/472

Causes the ROS2 humble builds to fail with error:
... /pcl_conversions/include/pcl_conversions/pcl_conversions.h:44:10: fatal error: message_filters/message_event.hpp: No such file or directory
44 | #include <message_filters/message_event.hpp>

This is caused by the fact that rolling version has both the *.h and *.hpp versions for the files message_event and message_traits. But humble version does not.

Suggestion: 
add also for humble the *.hpp versions for these headers.

**Comment by ahcorde** [comment]
There is a branch for `humble` in this repository https://github.com/ros-perception/perception_pcl/tree/humble. You should use this one to compile with Humble
