### ISSUE TITLE
Potential memory leaks in message_filters

### ISSUE THREAD

**Issue by SteveMacenski** [ros2/message_filters#49]
Hi,

Per https://github.com/ros-planning/navigation2/issues/1889, we're seeing memory leaks in Navigation2 in servers that make use of message filters that we believe message filters is the root cause (potentially could be TF2 ROS within message filters).

**Comment by clalancette** [comment]
It would be interesting to retry the test with Rolling.  We've fixed a few memory leaks in tf2_ros there, but we haven't been able to backport all of them to Foxy (since they break ABI; see https://github.com/ros2/geometry2/pull/330 for an in-progress PR).

**Comment by SteveMacenski** [comment]
Would the master branch be acceptable as well? We don't use rolling, we run master.

**Comment by clalancette** [comment]
> Would the master branch be acceptable as well? We don't use rolling, we run master nightly builds.

Yeah, that would also work.  It's preferable, honestly, since sometimes there is a delay between when we merge things and when it makes it to the Rolling packages.

**Comment by SteveMacenski** [comment]
I just don't use rolling on anything I maintain because I refuse to deal with the onslaught of emails it generates. I actually had to drop maintaining image pipeline for that reason (some small things break, suddenly I have `3 * number of packages in repo` emails in my inbox, daily).

**Comment by clalancette** [comment]
I believe this should be fixed in Foxy and on the master branches now (via https://github.com/ros2/geometry2/pull/330).  @SteveMacenski can you confirm?

**Comment by SteveMacenski** [comment]
Yes, we closed it in regards to that patch, thanks for bringing that home
