### ISSUE TITLE
 I'd like to know if i want information fusion between two built-in interfaces（like sensor_msg/image and geomory_msg/pose）. Is there an example？

### ISSUE THREAD

**Issue by IDCARDBORING** [ros2/message_filters#70]

**Comment by IDCARDBORING** [comment]
in ros1，i can 
  typedef message_filters::sync_policies::ApproximateTime<sensor_msgs::Image, geometry_msgs::PoseStamped> 
  SyncPolicyImagePose;
  typedef shared_ptr<message_filters::Synchronizer<SyncPolicyImagePose>> SynchronizerImagePose;
SynchronizerImagePose sync_image_pose_;
sync_image_pose_.reset(new message_filters::Synchronizer<SyncPolicyImagePose>(
      SyncPolicyImagePose(100), *depth_sub_, *pose_sub_));
  sync_image_pose_->registerCallback(boost::bind(&depthPoseCallback, this, _1, _2));

**Comment by aprotyas** [comment]
I would suggest redirecting questions like this to https://answers.ros.org/.

**Comment by IDCARDBORING** [comment]
> 

thanks!
