### ISSUE TITLE
How to use 'ApproximateTime' in ROS2?

### ISSUE THREAD

**Issue by PanZhichen** [ros2/message_filters#78]
https://github.com/ros2/message_filters/blob/5daf335b64f3b8ab88d97c69e44710e225c1b7c4/include/message_filters/time_synchronizer.h#L83

only find 'TimeSynchronizer' here.

**Comment by clalancette** [comment]
For questions like this, please ask on https://answers.ros.org, which is our central question and answer site.  You'll get a better answer there, and it will be searchable in the future.
