### ISSUE TITLE
Cannot create a vector of Subscriber dynamically

### ISSUE THREAD

**Issue by Minipada** [ros2/message_filters#86]
Hi, using Humble, I would like to create a dynamic amount of subscribers. With standard subscribers, I can do:

```cpp
std::vector<rclcpp::Subscription<msgType>::SharedPtr> subscriptions_;

for (auto& topic : topics_){ // topics_ is an std::vector<std::string>
    subscriptions_.push_back(node->create_subscription<msgType>(
        topic.c_str(), 10, std::bind(&MyClass::dataCb, this, std::placeholders::_1)));
}
```
And it works fine.

But when using Subscriber, the compiler returns an error since it inherits from noncopyable. I suppose there were some design choices leading to this. Is there any workaround or fix I could apply to handle this case?

Thanks!

**Comment by clalancette** [comment]
This should work:

```
  std::vector<std::shared_ptr<message_filters::Subscriber<Msg>>> subscriptions;
  for (const std::string & topic : topics) {
    subscriptions.emplace_back(std::make_unique<Subscriber<Msg>>(node, topic));
  }
```

In the future, for questions like this, please open them on https://answers.ros.org, which is our central question and answer site.  It will then be more easily searchable.
