### ISSUE TITLE
[Question] Why the limit of synchronizer is 9 topics?

### ISSUE THREAD

**Issue by Tumb1eweed** [ros2/message_filters#91]
Since c++11 already support variadic template, should synchronizer have no topic number limit or is it another way to achieve this without modifying it?

**Comment by clalancette** [comment]
> Since c++11 already support variadic template, should synchronizer have no topic number limit or is it another way to achieve this without modifying it?

I think it is mostly the fact that the synchronizer was written before C++11.  We'd be fine with having it rewritten with variadic templates, just nobody has had time to do it.  If you are interested in looking into it and opening a PR, we'd be happy to review.

**Comment by Tumb1eweed** [comment]
> > Since c++11 already support variadic template, should synchronizer have no topic number limit or is it another way to achieve this without modifying it?
> 
> I think it is mostly the fact that the synchronizer was written before C++11. We'd be fine with having it rewritten with variadic templates, just nobody has had time to do it. If you are interested in looking into it and opening a PR, we'd be happy to review.

Oh, i see the PR now, thanks for answering!
